### ISSUE TITLE
Slack notification is failing in Latest jenkins due to net.sf classes not found

### ISSUE THREAD

**Issue by abidk3** [jenkinsci/slack-plugin#1170]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Jenkins: 2.528.3
OS: Linux - 6.1.77-99.164.amzn2023.x86_64
Java: 17.0.10 - Amazon.com Inc. (OpenJDK 64-Bit Server VM)
---
allure-jenkins-plugin:2.34.0
amazon-ecr:1.114.vfd22430621f5
amazon-ecs:1.49
ansicolor:536.v13fa_b_860c267
ant:497.v94e7d9fffa_b_9
antisamy-markup-formatter:173.v680e3a_b_69ff3
apache-httpcomponents-client-4-api:4.5.14-269.vfa_2321039a_83
asm-api:9.9.1-189.vb_5ef2964da_91
authentication-tokens:1.53.v1c90fd9191a_b_
aws-credentials:254.v978a_5e206a_d7
aws-java-sdk-ec2:1.12.780-480.v4a_0819121a_9e
aws-java-sdk-ecr:1.12.633-430.vf9a_e567a_244f
aws-java-sdk-ecs:1.12.633-430.vf9a_e567a_244f
aws-java-sdk-efs:1.12.633-430.vf9a_e567a_244f
aws-java-sdk-minimal:1.12.780-480.v4a_0819121a_9e
aws-java-sdk2-core:2.33.4-62.vc1a_8df64b_4c9
aws-java-sdk2-ec2:2.33.4-62.vc1a_8df64b_4c9
blueocean:1.27.11
blueocean-bitbucket-pipeline:1.27.11
blueocean-commons:1.27.11
blueocean-config:1.27.11
blueocean-core-js:1.27.11
blueocean-dashboard:1.27.11
blueocean-display-url:2.4.2
blueocean-events:1.27.11
blueocean-git-pipeline:1.27.11
blueocean-github-pipeline:1.27.11
blueocean-i18n:1.27.11
blueocean-jwt:1.27.11
blueocean-personalization:1.27.11
blueocean-pipeline-api-impl:1.27.11
blueocean-pipeline-editor:1.27.11
blueocean-pipeline-scm-api:1.27.11
blueocean-rest:1.27.11
blueocean-rest-impl:1.27.11
blueocean-web:1.27.11
bootstrap5-api:5.3.7-860.v1251c115c90c
bouncycastle-api:2.30.1.82-277.v70ca_0b_877184
branch-api:2.1268.v044a_87612da_8
build-timeout:1.32
build-user-vars-plugin:212.vd6b_e9f6d0cdb_
caffeine-api:3.2.3-194.v31a_b_f7a_b_5a_81
checks-api:373.vfe7645102093
cloudbees-bitbucket-branch-source:877.vb_b_d5243f6794
cloudbees-folder:6.1073.va_7888eb_dd514
command-launcher:123.v37cfdc92ef67
commons-lang3-api:3.20.0-109.ve43756e2d2b_4
commons-text-api:1.15.0-210.v7480a_da_70b_9e
config-file-provider:1006.vc7366c201f57
copyartifact:722.v0662a_9b_e22a_c
credentials:1480.v2246fd131e83
credentials-binding:702.vfe613e537e88
dark-theme:439.vdef09f81f85e
display-url-api:2.217.va_6b_de84cc74b_
docker-commons:439.va_3cb_0a_6a_fb_29
docker-workflow:572.v950f58993843
durable-task:550.v0930093c4b_a_6
echarts-api:6.0.0-1146.v5c8f3b_8f0573
eddsa-api:0.3.0.1-19.vc432d923e5ee
email-ext:2.104
extended-choice-parameter:376.v2e02857547b_a_
favorite:2.208.v91d65b_7792a_c
font-awesome-api:7.0.0-851.vd1feb_218a_a_63
gatling:1.3.0
git:5.2.1
git-client:4.6.0
github:1.38.0
github-api:1.318-461.v7a_c09c9fa_d63
github-branch-source:1772.va_69eda_d018d4
global-slack-notifier:1.5
gradle:2.10
gson-api:2.13.1-153.vb_3d0c48a_a_b_4a_
handy-uri-templates-2-api:2.1.8-30.v7e777411b_148
htmlpublisher:1.32
instance-identity:203.v15e81a_1b_7a_38
ionicons-api:94.vcc3065403257
jackson2-api:2.20.1-423.v13951f6b_6532
jakarta-activation-api:2.1.3-2
jakarta-mail-api:2.1.3-3
jakarta-xml-bind-api:4.0.6-12.vb_1833c1231d3
javax-activation-api:1.2.0-8
javax-mail-api:1.6.2-11
jaxb:2.3.9-133.vb_ec76a_73f706
jdk-tool:83.v417146707a_3d
jenkins-design-language:1.27.11
jersey2-api:2.42-147.va_28a_44603b_d5
jira:3.13
jira-trigger:1.0.3
jjwt-api:0.11.5-77.v646c772fddb_0
joda-time-api:2.14.0-177.vd7e9347b_e7d5
jquery3-api:3.7.1-594.vb_3864f326cf0
json-api:20250517-173.v596efb_962a_31
json-path-api:2.10.0-202.va_9cc16c1e476
junit:1355.v45e2ea_65863c
ldap:711.vb_d1a_491714dc
mailer:522.va_995fa_cfb_8b_d
matrix-auth:3.2.8
matrix-project:856.v4c352b_3a_b_23e
mina-sshd-api-common:2.16.0-167.va_269f38cc024
mina-sshd-api-core:2.16.0-167.va_269f38cc024
nodejs:1.6.6
okhttp-api:4.11.0-172.vda_da_1feeb_c6e
pam-auth:1.10
parameterized-scheduler:262.v00f3d90585cc
pipeline-build-step:540.vb_e8849e1a_b_d8
pipeline-github-lib:42.v0739460cda_c4
pipeline-graph-analysis:216.vfd8b_ece330ca_
pipeline-groovy-lib:704.vc58b_8890a_384
pipeline-input-step:491.vb_07d21da_1a_fb_
pipeline-milestone-step:111.v449306f708b_7
pipeline-model-api:2.2277.v00573e73ddf1
pipeline-model-definition:2.2175.v76a_fff0a_2618
pipeline-model-extensions:2.2277.v00573e73ddf1
pipeline-rest-api:2.34
pipeline-stage-step:322.vecffa_99f371c
pipeline-stage-tags-metadata:2.2175.v76a_fff0a_2618
pipeline-stage-view:2.34
pipeline-utility-steps:2.16.2
plain-credentials:199.v9f8e1f741799
plugin-util-api:6.1167.v022176c7e0ca_
pubsub-light:1.18
resource-disposer:0.23
role-strategy:713.vb_3837801b_8cc
scm-api:724.v7d839074eb_5c
script-security:1385.v7d2d9ec4d909
slack:684.v833089650554
snakeyaml-api:2.3-125.v4d77857a_b_402
sse-gateway:1.26
ssh-credentials:361.vb_f6760818e8c
ssh-slaves:2.948.vb_8050d697fec
sshd:3.374.v19b_d59ce6610
strict-crumb-issuer:2.1.1
structs:362.va_b_695ef4fdf9
theme-manager:215.vc1ff18d67920
timestamper:1.26
token-macro:477.vd4f0dc3cb_cf1
trilead-api:2.209.v0e69b_c43c245
uno-choice:2.8.3
variant:70.va_d9f17f859e0
view-job-filters:369.ve0513a_a_f5524
workflow-aggregator:596.v8c21c963d92d
workflow-api:1384.vdc05a_48f535f
workflow-basic-steps:1042.ve7b_140c4a_e0c
workflow-cps:4252.v465f588eb_52f
workflow-durable-task-step:1331.vc8c2fed35334
workflow-job:1559.va_a_533730b_ea_d
workflow-multibranch:773.vc4fe1378f1d5
workflow-scm-step:466.va_d69e602552b_
workflow-step-api:710.v3e456cc85233
workflow-support:976.vb_d9493c2eb_09
ws-cleanup:0.45
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Amazon Linux 2023 - single node

### Reproduction steps

Use Slack Notification plugin after updating jenkins to 2.528.3

### Expected Results

Slack notification should be sent successfully.

### Actual Results

java.lang.ClassNotFoundException: net.sf.json.groovy.JsonSlurper
Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: 28ff5669-ef52-4def-913d-5358cb6c8d45
Caused: java.lang.NoClassDefFoundError: net/sf/json/groovy/JsonSlurper
	at PluginClassLoader for slack//jenkins.plugins.slack.workflow.SlackSendStep$SlackSendStepExecution.convertStringToJsonArray(SlackSendStep.java:404)
	at PluginClassLoader for slack//jenkins.plugins.slack.workflow.SlackSendStep$SlackSendStepExecution.getAttachmentsAsJSONArray(SlackSendStep.java:428)
	at PluginClassLoader for slack//jenkins.plugins.slack.workflow.SlackSendStep$SlackSendStepExecution.run(SlackSendStep.java:335)
	at PluginClassLoader for slack//jenkins.plugins.slack.workflow.SlackSendStep$SlackSendStepExecution.run(SlackSendStep.java:258)
	at PluginClassLoader for workflow-step-api//org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:49)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Finished: FAILURE

**Comment by abidk3** [comment]
There seems to be a removal of JSONSlurper from net.sf in jenkins fork. Possibly slack is affected as mentioned in the issue.

https://github.com/jenkinsci/json-lib/pull/81/files
